# Generated by Django 4.2.7 on 2025-07-20 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome del Progetto')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione del Progetto')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('collaboratori', models.ManyToManyField(blank=True, related_name='collaboratori_progetti', to=settings.AUTH_USER_MODEL, verbose_name='Collaboratori')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietario_progetti', to=settings.AUTH_USER_MODEL, verbose_name='Proprietario')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('stato', models.CharField(choices=[('TODO', 'Da Fare'), ('IN_PROGRESS', 'In Corso'), ('DONE', 'Completato')], default='TODO', max_length=20, verbose_name='Stato')),
                ('scadenza', models.DateTimeField(blank=True, null=True, verbose_name='Scadenza')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('assegnatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assegnati', to=settings.AUTH_USER_MODEL, verbose_name='Assegnato a')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_creati', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='progetti.progetto', verbose_name='Progetto')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
